### PR TITLE
Docker images and orchestration

### PR DESCRIPTION
**Pull request by rienafairefr**
This should be in the right direction for a dockerized instance of TardisBank, using Dockerfile for the API, web-app client, and db.

### CODE REVIEW

**Comment by mikehadlow** [comment]
Hi Matthieu, welcome to the TardisBank project, what brings you here? 
Many thanks for this contribution. I wonder if @keithbloom has anything to add. I know he was interested in this?

**Comment by rienafairefr** [comment]
Long winded road to here, I found http://tardisbank.com/ because I was looking at your blog for some post that I can't remember, found the project intersting, and found out you were doing a github for it so I watched it and saw your discussions involving docker these few days so I guess I thought hey I can do that, and wanted to spin up my own tardisbank :-)

**Comment by mikehadlow** [comment]
Thanks Matthieu. Of course you know that tardisbank.com and this project are completely separate. This is a from-the-ground-up rewrite. @keithbloom is looking at implementing the UI as an SPA, I'm just doing the API. The plan is to use it as a sample application for various ideas we've got. I know Keith was very interested in containerising it, while I've yet to get up to speed with all things Docker so I'd really like to get his input on this PR if that's OK. Otherwise it'd be great to have you onboard!

**Comment by mikehadlow** [comment]
BTW, the code for the original Tardis Bank is here: https://github.com/mikehadlow/Suteki.TardisBank

**Comment by rienafairefr** [comment]
Yep, I knew this was a rewrite, which is fine by me, a modern rewrite is usually good :+1: 
There was still a weird point about the node.js package.json proxy (redirecting /api to localhost:5000) which I had to change to redirect to the correct container, and I'm not sure how all that works, I'm more of a backend guy, not knowing a lot about React. He defintely needs to look at the changes to that web-app part, merging this will break his dev workflow AFAIK

**Comment by keithbloom** [comment]
Hi Matthieu 

Thanks very much for the PR, it looks like you’ve done everything I was thinking of 👍. I’ll pull the changes down and have a play locally. I’m interested in testing the proxy change you mentioned and how that impacts local dev. I think we’ll need a separate build of the client for the docker container and probably a web server that handles the routing of requests.

**Comment by rienafairefr** [comment]
I've pushed an improved version, with a `npm run build` and static deploy (nginx web server), no need to mess around the package.json :+1:

**Comment by mikehadlow** [comment]
Thanks Matthieu,
Merged :)

**Pull request merged**
